# Generated by Django 5.1.1 on 2024-09-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_review_reviewer_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='user_id',
        ),
    ]
