# Generated by Django 5.1.1 on 2024-10-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_reviewer_review_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='reviewer',
        ),
    ]
